apiVersion: apps/v1
kind: Deployment
metadata:
  name: triptik-staging
  labels:
    app: triptik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triptik
      provides: staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: triptik
        provides: staging
    spec:
      containers:
        - name: triptik
          image: gcr.io/mta-music-318515/triptik:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: triptik_staging
            - name: DB_NAME
              value: triptik_staging
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database
                  key: triptik-staging
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-directions-api-staging
                  key: key
            - name: PORT
              value: "80"
            - name: DEBUG
              value: "app:*"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: triptik-staging
  labels:
    app: triptik
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: triptik
    provides: staging
